# Generated by Django 3.1.7 on 2021-03-16 11:26

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("documents", "1037_webp_encrypted_thumbnail_conversion"),
    ]

    operations = [
        migrations.CreateModel(
            name="ConfigurationOption",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.CharField(max_length=128, unique=True)),
                ("value", models.CharField(blank=True, max_length=1024, null=True)),
            ],
        ),
    ]
