# Generated by Django 4.1.11 on 2023-09-24 17:12

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("documents", "1039_consumptiontemplate"),
    ]

    operations = [
        migrations.AddField(
            model_name="consumptiontemplate",
            name="is_insensitive",
            field=models.BooleanField(default=True, verbose_name="is insensitive"),
        ),
        migrations.AddField(
            model_name="consumptiontemplate",
            name="match",
            field=models.CharField(blank=True, max_length=256, verbose_name="match"),
        ),
        migrations.AddField(
            model_name="consumptiontemplate",
            name="matching_algorithm",
            field=models.PositiveIntegerField(
                choices=[
                    (0, "None"),
                    (1, "Any word"),
                    (2, "All words"),
                    (3, "Exact match"),
                    (4, "Regular expression"),
                    (5, "Fuzzy word"),
                ],
                default=0,
                verbose_name="matching algorithm",
            ),
        ),
    ]
